limenius_react:
    # Other options are "server_side" and "client_side"
    #default_rendering: "both"
    default_rendering: "both"
    serverside_rendering:
        # In case of error in server-side rendering, throw exception
        fail_loud: false
        # Replay every console.log message produced during server-side rendering
        # in the JavaScript console
        # Note that if enabled it will throw a (harmless) React warning
        trace: false
        # Mode can be `"phpexecjs"` (to execute Js from PHP using PhpExecJs),
        # or `"external_server"` (to rely on an external node.js server)
        # Default is `"phpexecjs"`
        mode: "phpexecjs"
        # Only used with mode `phpexecjs`
        #  Location of the server bundle, that contains React and React on Rails.
        #  null will default to `%kernel.root_dir%/Resources/webpack/server-bundle.js`
        server_bundle_path: "%kernel.project_dir%/var/webpack/server-bundle.js"
        # Only used with mode `external`
        #  Location of the unix socket to communicate with a dummy node.js server
        #  Such as the one in `Resources/node-server/server.js`
        #  null will default to `%kernel.project_dir%/var/node.sock
        server_socket_path: null
